site_name: Siddhi Map Json
site_description: Siddhi Map Json Extension
site_author: WSO2
site_url: https://wso2-extensions.github.io/siddhi-map-json/
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
repo_name: Siddhi-Map-Json
repo_url: https://github.com/wso2-extensions/siddhi-map-json
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
- Welcome: index.md
- API Docs:
  - 4.0.36: api/4.0.36.md
  - 4.0.35: api/4.0.35.md
  - 4.0.34: api/4.0.34.md
  - 4.0.33: api/4.0.33.md
  - 4.0.32: api/4.0.32.md
  - 4.0.31: api/4.0.31.md
  - 4.0.30: api/4.0.30.md
  - 4.0.29: api/4.0.29.md
  - 4.0.28: api/4.0.28.md
  - 4.0.27: api/4.0.27.md
  - 4.0.26: api/4.0.26.md
  - 4.0.25: api/4.0.25.md
  - 4.0.24: api/4.0.24.md
  - 4.0.23: api/4.0.23.md
  - 4.0.22: api/4.0.22.md
  - 4.0.21: api/4.0.21.md
  - 4.0.20: api/4.0.20.md
  - 4.0.19: api/4.0.19.md
  - 4.0.18: api/4.0.18.md
  - 4.0.17: api/4.0.17.md
  - latest: api/latest.md
- License: about/license.md
